### ISSUE TITLE
Follow path should have 2 strategies: Rigid and Smooth

### ISSUE THREAD

**Issue by wacaine** [decentraland/sdk7-utils#2]
https://github.com/decentraland/sdk7-utils/blob/393f3f8de94f0d67d70ef34b206b8598210fce52/src/path.ts#L47

When we zero out the value (assign 0 to it) it can cause jitters when moving faster and low FPS as it transitions between 1 segment to the other.  The object position gets set to 0 for next segment when we should instead carry forward the excess so the lerp is smoother.

I can see use cases for both

RIGID - if you need the object to hit each point exactly.  Like hitting each point of a structure like the points of a star shape
SMOOTH - if you need the path to be smooth even if it cuts corners

See how NPC utils did it

https://github.com/decentraland/decentraland-npc-utils/blob/main/src/npc/move.ts#L41

**Comment by AN-DCL** [comment]
Version 1.0.1 (latest) has FPS-independent (SMOOTH) paths. Not sure why previous, FPS-dependent (RIGID) option is needed.

**Comment by wacaine** [comment]
@AN-DCL  rigid is if you need the thing following to exactly hit the point.  Think traveling a 5 point star with sharp corners the lerp will likely cut corners.   Smooth will cut the corner.  Could be a need for one over the other.  My gut says SMOOTH is the more common wan.  RIDGID may have use cases though

**Comment by wacaine** [comment]
I still see SMOOTH is not implemented

https://github.com/decentraland/sdk7-utils/blob/393f3f8de94f0d67d70ef34b206b8598210fce52/src/path.ts#L47

To achieve smooth you need to keep track of the overage.  Otherwise when they go to next segment, the lerp starts at 0 when it really should be .001 or what ever overage was not carried forward

path.normalizedTime = 1- path.normalizedTime

**Comment by AN-DCL** [comment]
> I still see SMOOTH is not implemented

It is implemented. You're quoting some ancient commit.

**Comment by wacaine** [comment]
Got it I was looking at older code.  This looks better.   All good

**Comment by wacaine** [comment]
1.0.1 version  there's no longer per segment normalized time. There's a normalized time for the whole path, and an entity is placed at proper position on a proper segment according to this time.  Should fix issue
